### PR TITLE
[kf5-kdoctools] Modify caveats with proper command

### PR DESCRIPTION
**Pull request by franklinyu**
If user linked from `Application Support` to `opt/kf5-kdoctools/share`, he would be only accessing the `kf5` folder of this formula. The correct way is to link to the one in Homebrew root.

Thank @sl1pkn07 for ideas in https://github.com/KDE-mac/homebrew-kde/issues/141#issuecomment-341936230.

### CODE REVIEW

**Comment by franklinyu** [comment]
The build failed because of lack of Perl module. Shall we add that into Travis build script?

**Comment by yurikoles** [comment]
@franklinyu yes please add a cpanm command to travis file.

**Comment by yurikoles** [comment]
@franklinyu I did it by myself

**Comment by sl1pkn07** [comment]
i thinks is better move this caveats outside kdoctools and move to extra-cmake-modules. in kdoctools do nothing, and in extra-cmake-modules is the common package used by all kde/kde apps/frameworks

**Comment by yurikoles** [comment]
@sl1pkn07 hi there! Whatsapp with your branch? When we will see a PR?

**Comment by sl1pkn07** [comment]
https://github.com/sl1pkn07/homebrew-kde/tree/sl1pkn07

**Comment by franklinyu** [comment]
CMake doesn't seem able to find `URI::Escape`… Do we need to explicitly specify the directory `~/perl5` to Homebrew? Or `eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)` [here](https://travis-ci.org/KDE-mac/homebrew-kde/builds/297568886#L1623) should have done it?

**Comment by sl1pkn07** [comment]
seems travis failed when ser cman uri

https://travis-ci.org/KDE-mac/homebrew-kde/builds/301084974#L2071

**Pull request merged**
