### PR TITLE
[WIP] New formula: KCalc

### PR DESCRIPTION
**Pull request by sadhen**
see #268

### CODE REVIEW

**Comment by yurikoles** [comment]
Please remove all deps except cmake and search for deps that cmake has failed to find.

**Comment by yurikoles** [comment]
And also please change home page URL.

**Comment by sadhen** [comment]
Well, just fixed a bug for Okular. I will complete this PR later.

**Comment by sadhen** [comment]
This pull request serves as a demo. I will polish it later and add detailed comments for beginners.

**Comment by yurikoles** [comment]
@sadhen any news?

**Comment by sadhen** [comment]
@yurikoles really busy these days. I will complete this PR with a wiki or blog post later.

And the PR submitted upstream (Okular and Konversation) should be carefully polished.

**Pull request closed without merging**
