### PR TITLE
Fix installation of dolphin

### PR DESCRIPTION
**Pull request by arichardson**
Dolphin previously failed to install for me because the kdelibs4support dependency was missing.
After I added that dependency I got a dependency conflict between `openssl` and `openssl@1.1` due to the kio-extras dependency. I've now updated kdelibs4support to use `openssl` instead which fixes the issue for me. With these changes I was able to launch dolphin and browse files.

### CODE REVIEW

**Comment by sl1pkn07** [comment]
https://cgit.kde.org/dolphin.git/log/?qt=grep&q=kdelibs4support

kdelibs4support is pulled by other framework package. i need find what and why

**Comment by sl1pkn07** [comment]
also:

```
└───╼  grep -R openssl *
cyrus-sasl.rb:  depends_on "openssl"
cyrus-sasl.rb:           "CFLAGS=-I#{HOMEBREW_PREFIX}/opt/openssl/include ",
cyrus-sasl.rb:           "LDFLAGS=-L#{HOMEBREW_PREFIX}/opt/openssl/lib",
kf5-kdelibs4support.rb:  depends_on "openssl@1.1"
kf5-khtml.rb:  depends_on "openssl@1.1"
```

none of kf5 packages needs openssl. seems is pulled by other package.

**Comment by sl1pkn07** [comment]
~~~bash
└───╼  brew install -v dolphin.rb
Updating Homebrew...
/usr/bin/sandbox-exec -f /tmp/homebrew20171117-76905-73o5d2.sb nice /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/build.rb /Volumes/Home/Hakintoch/aplicaciones/homebrew-kde/dolphin.rb --verbose
==> Downloading https://download.kde.org/stable/applications/17.08.3/src/dolphin-17.08.3.tar.xz
Already downloaded: /Volumes/Home/Hakintoch/Library/Caches/Homebrew/dolphin-17.08.3.tar.xz
==> Verifying dolphin-17.08.3.tar.xz checksum
tar xJf /Volumes/Home/Hakintoch/Library/Caches/Homebrew/dolphin-17.08.3.tar.xz
==> cmake .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/dolphin/17.08.3 -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=ON -Wno-dev -DBUILD_TESTING=OFF -DKDE_INSTALL_QMLDIR=lib/qt5/qml -DKDE_INSTALL_PLUGINDIR=lib/qt5/plugins -DCMAKE_INSTALL_BUNDLEDIR=/usr/local/Cellar/dolphin/17.08.3/bin
-- The C compiler identification is AppleClang 9.0.0.9000038
-- The CXX compiler identification is AppleClang 9.0.0.9000038
-- Check for working C compiler: /usr/local/Homebrew/Library/Homebrew/shims/super/clang
-- Check for working C compiler: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/local/Homebrew/Library/Homebrew/shims/super/clang++
-- Check for working CXX compiler: /usr/local/Homebrew/Library/Homebrew/shims/super/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning at /usr/local/share/ECM/kde-modules/KDECMakeSettings.cmake:266 (message):
  Searching for X11 and related technologies is disabled on Apple systems.
  Set APPLE_FORCE_X11 to ON to change this behaviour.  Set
  APPLE_SUPPRESS_X11_WARNING to ON to hide this warning.
Call Stack (most recent call first):
  CMakeLists.txt:25 (include)


-- Looking for __GLIBC__
-- Looking for __GLIBC__ - not found
-- Performing Test _OFFT_IS_64BIT
-- Performing Test _OFFT_IS_64BIT - Success
-- Performing Test HAVE_DATE_TIME
-- Performing Test HAVE_DATE_TIME - Success
-- Found KF5DocTools: /usr/local/lib/cmake/KF5DocTools/KF5DocToolsConfig.cmake (found version "5.40.0") 
-- Found KF5Init: /usr/local/lib/cmake/KF5Init/KF5InitConfig.cmake (found version "5.40.0") 
-- Found KF5KCMUtils: /usr/local/lib/cmake/KF5KCMUtils/KF5KCMUtilsConfig.cmake (found version "5.40.0") 
-- Found KF5NewStuff: /usr/local/lib/cmake/KF5NewStuff/KF5NewStuffConfig.cmake (found version "5.40.0") 
-- Found KF5CoreAddons: /usr/local/lib/cmake/KF5CoreAddons/KF5CoreAddonsConfig.cmake (found version "5.40.0") 
-- Found Gettext: /usr/local/opt/gettext/bin/msgmerge (found version "0.19.8.1") 
-- Found PythonInterp: /usr/bin/python (found version "2.7.10") 
-- Found KF5I18n: /usr/local/lib/cmake/KF5I18n/KF5I18nConfig.cmake (found version "5.40.0") 
-- Found KF5DBusAddons: /usr/local/lib/cmake/KF5DBusAddons/KF5DBusAddonsConfig.cmake (found version "5.40.0") 
-- Found KF5Bookmarks: /usr/local/lib/cmake/KF5Bookmarks/KF5BookmarksConfig.cmake (found version "5.40.0") 
-- Found KF5Config: /usr/local/lib/cmake/KF5Config/KF5ConfigConfig.cmake (found version "5.40.0") 
-- Found KF5KIO: /usr/local/lib/cmake/KF5KIO/KF5KIOConfig.cmake (found version "5.40.0") 
-- Found KF5Parts: /usr/local/lib/cmake/KF5Parts/KF5PartsConfig.cmake (found version "5.40.0") 
-- Found KF5Solid: /usr/local/lib/cmake/KF5Solid/KF5SolidConfig.cmake (found version "5.40.0") 
-- Found KF5IconThemes: /usr/local/lib/cmake/KF5IconThemes/KF5IconThemesConfig.cmake (found version "5.40.0") 
-- Found KF5Completion: /usr/local/lib/cmake/KF5Completion/KF5CompletionConfig.cmake (found version "5.40.0") 
-- Found KF5TextWidgets: /usr/local/lib/cmake/KF5TextWidgets/KF5TextWidgetsConfig.cmake (found version "5.40.0") 
-- Found KF5Notifications: /usr/local/lib/cmake/KF5Notifications/KF5NotificationsConfig.cmake (found version "5.40.0") 
-- Found KF5Crash: /usr/local/lib/cmake/KF5Crash/KF5CrashConfig.cmake (found version "5.40.0") 
-- Found KF5: success (found suitable version "5.40.0", minimum required is "5.30.0") found components:  DocTools Init KCMUtils NewStuff CoreAddons I18n DBusAddons Bookmarks Config KIO Parts Solid IconThemes Completion TextWidgets Notifications Crash 
-- Found KF5Activities: /usr/local/lib/cmake/KF5Activities/KF5ActivitiesConfig.cmake (found version "5.40.0") 
-- Found KF5: success (found suitable version "5.40.0", minimum required is "5.30.0") found components:  Activities 
CMake Warning at CMakeLists.txt:75 (find_package):
  By not providing "FindKF5Baloo.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "KF5Baloo",
  but CMake did not find one.

  Could not find a package configuration file provided by "KF5Baloo"
  (requested version 4.97) with any of the following names:

    KF5BalooConfig.cmake
    kf5baloo-config.cmake

  Add the installation prefix of "KF5Baloo" to CMAKE_PREFIX_PATH or set
  "KF5Baloo_DIR" to a directory containing one of the above files.  If
  "KF5Baloo" provides a separate development package or SDK, be sure it has
  been installed.


CMake Warning at CMakeLists.txt:82 (find_package):
  By not providing "FindKF5BalooWidgets.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "KF5BalooWidgets", but CMake did not find one.

  Could not find a package configuration file provided by "KF5BalooWidgets"
  (requested version 4.97) with any of the following names:

    KF5BalooWidgetsConfig.cmake
    kf5baloowidgets-config.cmake

  Add the installation prefix of "KF5BalooWidgets" to CMAKE_PREFIX_PATH or
  set "KF5BalooWidgets_DIR" to a directory containing one of the above files.
  If "KF5BalooWidgets" provides a separate development package or SDK, be
  sure it has been installed.


-- Found KF5KDELibs4Support: /usr/local/lib/cmake/KF5KDELibs4Support/KF5KDELibs4SupportConfig.cmake (found version "5.40.0") 
-- Found KF5: success (found suitable version "5.40.0", minimum required is "5.30.0") found components:  KDELibs4Support 
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Success
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Success
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
-- The following OPTIONAL packages have been found:

 * KF5Activities (required version >= 5.30.0)
 * KF5FileMetaData (required version >= 5.19.0), <https://projects.kde.org/kfilemetadata>
   For accessing file metadata labels

-- The following REQUIRED packages have been found:

 * ECM (required version >= 1.6.0)
 * Qt5Core
 * Qt5Concurrent
 * Qt5Widgets
 * Qt5Gui
 * Qt5DBus
 * Qt5 (required version >= 5.5.0)
 * KF5DocTools (required version >= 5.30.0)
 * KF5Init (required version >= 5.30.0)
 * KF5KCMUtils (required version >= 5.30.0)
 * KF5NewStuff (required version >= 5.30.0)
 * KF5CoreAddons (required version >= 5.30.0)
 * Gettext
 * PythonInterp
 * KF5I18n (required version >= 5.30.0)
 * KF5DBusAddons (required version >= 5.30.0)
 * KF5Bookmarks (required version >= 5.30.0)
 * KF5Config (required version >= 5.30.0)
 * KF5KIO (required version >= 5.30.0)
 * KF5Parts (required version >= 5.30.0)
 * KF5Solid (required version >= 5.30.0)
 * KF5IconThemes (required version >= 5.30.0)
 * KF5Completion (required version >= 5.30.0)
 * KF5TextWidgets (required version >= 5.30.0)
 * KF5Notifications (required version >= 5.30.0)
 * KF5Crash (required version >= 5.30.0)
 * Phonon4Qt5
 * KF5KDELibs4Support (required version >= 5.30.0)
 * KF5 (required version >= 5.30.0)

-- The following OPTIONAL packages have not been found:

 * KF5Baloo (required version >= 4.97), Baloo Core libraries, <http://www.kde.org>
   For adding desktop-wide search and tagging support to dolphin
 * KF5BalooWidgets (required version >= 4.97), Baloos Widgets, <http://www.kde.org>

-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/dolphin-20171117-76907-1tgi1iz/dolphin-17.08.3/build
==> make install
/usr/local/Cellar/cmake/3.9.6/bin/cmake -H/tmp/dolphin-20171117-76907-1tgi1iz/dolphin-17.08.3 -B/tmp/dolphin-20171117-76907-1tgi1iz/dolphin-17.08.3/build --check-build-system CMakeFiles/Makefile.cmake 0
/usr/local/Cellar/cmake/3.9.6/bin/cmake -E cmake_progress_start /tmp/dolphin-20171117-76907-1tgi1iz/dolphin-17.08.3/build/CMakeFiles /tmp/dolphin-20171117-76907-1tgi1iz/dolphin-17.08.3/build/CMakeFiles/progress.marks
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f CMakeFiles/Makefile2 all
--snip--
ln -s ../../../Cellar/dolphin/17.08.3/lib/qt5/plugins/kcm_dolphinservices.so kcm_dolphinservices.so
ln -s ../../../Cellar/dolphin/17.08.3/lib/qt5/plugins/kcm_dolphinviewmodes.so kcm_dolphinviewmodes.so
/usr/bin/sandbox-exec -f /tmp/homebrew20171117-78571-1f8kytg.sb nice /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby -W0 -I /usr/local/Homebrew/Library/Homebrew -- /usr/local/Homebrew/Library/Homebrew/postinstall.rb /Volumes/Home/Hakintoch/aplicaciones/homebrew-kde/dolphin.rb -v
==> Caveats
You need to take some manual steps in order to make this formula work:
  ln -sf "$(brew --prefix)/share/dolphin" ~/Library/"Application Support"
  ln -sf "$(brew --prefix)/share/config.kcfg" ~/Library/"Application Support"
  mkdir -p ~/Applications/KDE
  ln -sf "/usr/local/opt/dolphin/bin/dolphin.app" ~/Applications/KDE/
==> Summary
🍺  /usr/local/Cellar/dolphin/17.08.3: 231 files, 8.6MB, built in 3 minutes 2 seconds
~~~

**Comment by arichardson** [comment]
kio-extras needs libssh which in turn depends on libssh. How were you able to build dolphin? For me brew refused to build it without this patch.

**Comment by sl1pkn07** [comment]
please test this https://github.com/KDE-mac/homebrew-kde/pull/173

**Comment by arichardson** [comment]
I tried with 173 and I get the same error: kdelibs4support missing, and if I add it I get the conflict.
This patch is pretty trivial and gives me a running dolphin.

**Comment by sl1pkn07** [comment]
how you install dolphin? first the all kf5 frameworks? or dolphin directly

**Comment by arichardson** [comment]
`brew install dolphin`

**Comment by sl1pkn07** [comment]
ok. you are right. something wrong happen in Brew with the dependency tracking

add kfilemetadata (as depend_on) and kdelibs4suport (as :build depend) solve the issue (without openssl conflicts)

the strange is, if install kdelibs4support before dolphin (without add it in the depends list), and in dolphin add only kfilemetadata as depend, dolphin build without issue!! 

this is supposed have to happen???

is supposed brew only do permission to add the headers/libs depends if the depend is listed on the formula??

well this is the patch i used now:

~~~patch
diff --git a/dolphin.rb b/dolphin.rb
index f593f5c..e97bc68 100644
--- a/dolphin.rb
+++ b/dolphin.rb
@@ -10,6 +10,7 @@ class Dolphin < Formula
   depends_on "cmake" => :build
   depends_on "KDE-mac/kde/kf5-extra-cmake-modules" => :build
   depends_on "KDE-mac/kde/kf5-kdoctools" => :build
+  depends_on "KDE-mac/kde/kf5-kdelibs4support" => :build
 
   depends_on :ruby => ["2.4", :optional]
   depends_on "KDE-mac/kde/konsole" => [:run, :optional]
@@ -19,6 +20,7 @@ class Dolphin < Formula
   depends_on "KDE-mac/kde/kf5-knewstuff"
   depends_on "KDE-mac/kde/kf5-kparts"
   depends_on "KDE-mac/kde/kio-extras"
+  depends_on "KDE-mac/kde/kf5-kfilemetadata"
 
   def install
     args = std_cmake_args
diff --git a/kf5-kdelibs4support.rb b/kf5-kdelibs4support.rb
index 41ba546..e57df88 100644
--- a/kf5-kdelibs4support.rb
+++ b/kf5-kdelibs4support.rb
@@ -8,6 +8,7 @@ class Kf5Kdelibs4support < Formula
   head "git://anongit.kde.org/kdelibs4support.git"
 
   depends_on "cmake" => :build
+  depends_on "perl" => :build
   depends_on "KDE-mac/kde/kf5-extra-cmake-modules" => :build
   depends_on "KDE-mac/kde/kf5-kdesignerplugin" => :build
   depends_on "KDE-mac/kde/kf5-kdoctools" => :build
@@ -41,6 +42,10 @@ class Kf5Kdelibs4support < Formula
   end
 
   def caveats; <<-EOS.undent
+    Before install of this formula you need to run:
+      brew install cpanminus
+      cpanm URI
+
     You need to take some manual steps in order to make this formula work:
       ln -sf "$(brew --prefix)/share/kf5" "$HOME/Library/Application Support"
       ln -sf "$(brew --prefix)/share/kservices5" "$HOME/Library/Application Support"
~~~

or wait to my rebase in #173

greetings

**Comment by arichardson** [comment]
Yes that is expected, if you install kdelibs4support first, then all the headers and .cmake files will be found so dolphin can be compiled. This has nothing to do with kfilemetadata ( Of course kfilemetadata should still be added but it won't fix this issue). I tried with your added kffilemetadata and I still got the same error:

```
==> Installing kde-mac/kde/dolphin dependency: KDE-mac/kde/kf5-kfilemetadata
==> Downloading https://download.kde.org/stable/frameworks/5.40/kfilemetadata-5.40.0.tar.xz
==> Downloading from http://www.mirrorservice.org/sites/download.kde.org/stable/frameworks/5.40/kfilemetadata-5.40.0.
######################################################################## 100.0%
==> cmake .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Ce
==> make install
🍺  /usr/local/Cellar/kf5-kfilemetadata/5.40.0_1: 99 files, 1MB, built in 34 seconds
==> Installing kde-mac/kde/dolphin
==> Downloading https://download.kde.org/stable/applications/17.08.3/src/dolphin-17.08.3.tar.xz
Already downloaded: /Users/alex/Library/Caches/Homebrew/dolphin-17.08.3.tar.xz
==> cmake .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Ce
Last 15 lines from /Users/alex/Library/Logs/Homebrew/dolphin/01.cmake:

-- Could NOT find KF5KDELibs4Support (missing: KF5KDELibs4Support_DIR)
-- Could NOT find KF5KDELibs4Support: found neither KF5KDELibs4SupportConfig.cmake nor kf5kdelibs4support-config.cmake
CMake Error at /usr/local/Cellar/cmake/3.9.6/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find KF5 (missing: KDELibs4Support) (Required is at least version
  "5.30.0")
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.9.6/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:377 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/share/ECM/find-modules/FindKF5.cmake:110 (find_package_handle_standard_args)
  CMakeLists.txt:99 (find_package)


-- Configuring incomplete, errors occurred!
See also "/tmp/dolphin-20171120-75504-1wz4qia/dolphin-17.08.3/build/CMakeFiles/CMakeOutput.log".
See also "/tmp/dolphin-20171120-75504-1wz4qia/dolphin-17.08.3/build/CMakeFiles/CMakeError.log".
```

Why are you so opposed to merging this pull request?

**Comment by sl1pkn07** [comment]
I've rebased PR173 with my last change

I've remove libssh (I back it when libssh 0.8 release and Brew link it with openssl@1.1) in kio-extras and add kdelibs4support on dolphin

about my statement posted above, i've want mean, I've belive Brew working like sandbox/fakeroot and not add to search/compilation any source/lib if not add first to the depends list, but i see this is not true

and no, I've not merge you PR because i don't want "downgrade" openssl@1.1., i prefeer disable it if is not is strict necessary

please test it 

greetings

**Comment by arichardson** [comment]
kdelibs4support won't be around much longer anyway so why not just link that with openssl1.0? I is highly unlikely that the KSslSocket code is used anyway since most stuff is using QNetworkAccessManager or KIO anyway.

If you really want to prevent brew from finding already installed packages you will have to stop linking the headers/libraries for the frameworks into /usr/local and explicitly pass all the dependency directories in `CMAKE_PREFIX_PATH`.

**Comment by sl1pkn07** [comment]
>kdelibs4support won't be around much longer anyway

yes, but baloo support for macosx is not finished (or started), and dolphin use KFileMetaDataWidget included on kdelibs4support as replacement if not found baloo.

also, Qt 5.10 outs their final release in 30.11.2017, and include support for openssl 1.1, not need back, and up again in 10 days

>If you really want to prevent brew from finding already installed packages you will have to stop linking the headers/libraries for the frameworks into /usr/local and explicitly pass all the dependency directories in CMAKE_PREFIX_PATH.

thanks for the hint. this is good for test

greetings

**Comment by arichardson** [comment]
Seems to work now

**Pull request closed without merging**
