### PR TITLE
Add Kdenlive v18.04.3

### PR DESCRIPTION
**Pull request by fjperini**
It would be very good if we work on this formula! :smiley: I created a [repo](https://github.com/fjperini/homebrew-mytap) to upload the changes made in the formulas: `cantor`, `labplot`, `kdenlive`, `kalzium`, `molequeue`, `krename`, `krita`... and others!

kdenlive

Note: I made some changes for PURPOSE and LIBV4L2.

### CODE REVIEW

**Comment by yurikoles** [comment]
@fjperini please upstream commits in your fork via KDE phabricator. I can't accept a fork.

**Comment by fjperini** [comment]
@yurikoles Ok! I incorporate the changes using a `patch`, can you accept it? And contact the developers of `kdenlive` to review those changes and resolve the integration in macOS.

**Comment by fjperini** [comment]
It seems that compiles well from `kdenlive-18.04.3.tar.xz`, before: error with `PURPOSE` and `LIBV4L2`.

Note: for `ffmpeg`, you could

```
brew install ffmpeg $(brew options ffmpeg | grep -vE '\s' | grep -- '--with-' | tr '\n' ' ')
```
When starting the program it may be crash, I solved it changing in `/Library/Preferences/kdenliverc` from `true` to `false`: `Window-Maximized = false`

@yurikoles he jumped that error on Travis.

```
The command "tools/all-fixes.sh" failed and exited with 1 during .
```
You can now merge, using the official source.

**Comment by yurikoles** [comment]
merged via c7dfba06b17b3f321c3c80d58471cf5094cfb39f

**Pull request closed without merging**
