### PR TITLE
Fixed addition of QT_PLUGIN_PATH to environment

### PR DESCRIPTION
**Pull request by prakgoya**
Fixed addition of QT_PLUGIN_PATH to environment of KDevelop app

### CODE REVIEW

**Comment by prakgoya** [comment]
Hi @yurikoles, this seems to have broken the installation on macOS High Sierra (10.13.6). I'm working on a fix.

**Comment by yurikoles** [comment]
@prakgoya I had already fixed it in 79278122e4ec83ed5ebcfd67bcdf6e22e61ef5c9

**Comment by prakgoya** [comment]
Thanks @yurikoles. I apologize for any inconvenience caused. I'll be more careful in the future.

**Comment by yurikoles** [comment]
@prakgoya, no problem :)
`only those who do nothing make no mistakes`

**Pull request merged**
