### PR TITLE
The doomsday: my changes

### PR DESCRIPTION
**Pull request by sl1pkn07**
Have a tons of changes. i can't enumerate all

tested on my hackchine, all build OK (and some test in applications, more or less, all runs)

the only know issue is okular with openssl (1.0.x) reverse dependency (fail due conflicts in openssl@1.1 and openssl). any help?

also need touch the internal brew variables. i think do someting weird if build from HEAD (see the output on mymoney compared with other "packaged" formulas) 

also i need all of the help of the world for fix the issues when try merge this PR. what steps (like you explain it to a children) i need to do.

greetings

### CODE REVIEW

**Comment by pat-s** [comment]
Regarding the merge conflicts: Do `git merge master` and resolve all conflicts between your branch and master (by deleting unnecessary things in master) and then commit and push your branch.

**Comment by sl1pkn07** [comment]
thats is a general idea, but i what commands for do it!

**Comment by sl1pkn07** [comment]
at the moment, i' do "nanodized" (edit) all files and remove "HEAD" changes and keep the mine

i'ts ok?

**Comment by sl1pkn07** [comment]
YAI!!!!!

**Comment by pat-s** [comment]
Yes that's fine. What to do exactly depends of course on what editor/IDE you use.

**Pull request merged**
