### PR TITLE
Add KPeople formula

### PR DESCRIPTION
**Pull request by Inokinoki**
KDE Connect depends on KPeople and its extension: KPeopleVCard.

This PR add KPeople forumla
https://api.kde.org/frameworks/kpeople/html/index.html

### CODE REVIEW

**Comment by Inokinoki** [comment]
Should I rename it to `kf5-people.rb`?

**Comment by yurikoles** [comment]
Hi @Inokinoki,
We already have it here: [kf5-kpeople.rb](https://github.com/KDE-mac/homebrew-kde/blob/master/Formula/kf5-kpeople.rb).

**Comment by yurikoles** [comment]
Thanks for contribution, but please use search next time you want to add something, maybe it's already there :)

**Comment by Inokinoki** [comment]
> Thanks for contribution, but please use search next time you want to add something, maybe it's already there :)

Thanks for reminding ! It's my fault.

Then how about kpeoplevcard? KDE Connect actually depends on kpeoplevcard and thus indirectly depends on kpeople. Do you plan to include it into the forumlas?

**Pull request closed without merging**
