### PR TITLE
Revert "okular: qca not support openssl@1.1 (conflicts with kf5-khtml…

### PR DESCRIPTION
**Pull request by sl1pkn07**
…)" (fixed)

This reverts commit 20861fab0f4ef1a1b8dc67b49ddad6f61c986886.

### CODE REVIEW

**Comment by sl1pkn07** [comment]
@yurikoles give me tha powa!

**Comment by sl1pkn07** [comment]
@yurikoles i cant push my changes/pr to my branch, can you give me permissions?

**Comment by yurikoles** [comment]
Please provide your command and output.

**Comment by yurikoles** [comment]
@sl1pkn07 I had made you an owner

**Comment by sl1pkn07** [comment]
└───╼  LC_ALL=C git push
ERROR: Permission to KDE-mac/homebrew-kde.git denied to sl1pkn07.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by yurikoles** [comment]
@sl1pkn07 try again

**Comment by sl1pkn07** [comment]
yep. now seems working

i hope, for the shake of god, don't break anithing this time :S

**Pull request merged**
