### PR TITLE
solve 'undefined method `<=' for nil:NilClass'

### PR DESCRIPTION
**Pull request by pat-s**
See https://github.com/Homebrew/brew/issues/3442. 

This is blocking as no `brew` commands work anymore. 

The proposed fix works.

### CODE REVIEW

**Comment by sl1pkn07** [comment]
yep. and have the same problem with kf5-ktexteditor

is a problem with the updater-formulas script., this is fixed in my branch

btw, the openssl 1.1 patch is applied in upstream. not need anymore

**Comment by sl1pkn07** [comment]
```
        if ($line =~ /^\s*url\s+\"(.*)\"\s*$/) {
            next;
        }
        if ($line =~ /^\s*sha256\s+\"(.*)\"\s*$/) {
            next;
        }
```
should be 
```
        if ($line =~ /^\s*^  url\s+\"(.*)\"\s*$/) {
            next;
        }
        if ($line =~ /^\s*^  sha256\s+\"(.*)\"\s*$/) {
            next;
        }
```

**Comment by pat-s** [comment]
Ready to merge then? Since this is blocking for all users who tapped this repo this should be merged instantly.

**Comment by sl1pkn07** [comment]
right now is installing on my hackchine for see if need more touch. when finish and i see all ok. then yes

**Comment by sl1pkn07** [comment]
the patch of kf5-ktexteditor is also upstreamed

**Comment by sl1pkn07** [comment]
done

**Pull request closed without merging**
