### PR TITLE
A Retina Okular

### LINKED ISSUE #264: Okular - High dpi - Retina
Hi!

I`ve installed HEAD all packets. And I can launch  okular on my MacOS 10.14.1 but with low dpi. Is it possible run it on retina dpi?

### PR DESCRIPTION
**Pull request by sadhen**
fix #264

### CODE REVIEW

**Comment by yurikoles** [comment]
Please add `revision 1` after sha256 string. And please send a PR in KDE Phabricator as well.

**Comment by sadhen** [comment]
OK, too late over midnight now. I will do it later.

**Comment by yurikoles** [comment]
I can do it myself, just formally grant here in comment that your code is under Okular license terms.

**Comment by sadhen** [comment]
The CI hangs on download source code from a mirror of KDE.

**Comment by sadhen** [comment]
@yurikoles 

See

+ https://phabricator.kde.org/D17054
+ https://phabricator.kde.org/D17053

**Comment by yurikoles** [comment]
@sadhen thanks a lot!

**Comment by sadhen** [comment]
According the brew Caveats
```
==> Caveats
You need to take some manual steps in order to make this formula work:
  ln -sfv "$(brew --prefix)/share/okular" "$HOME/Library/Application Support"
  ln -sfv "$(brew --prefix)/share/kconf_update" "$HOME/Library/Application Support"
  ln -sfv "$(brew --prefix)/share/config.kcfg" "$HOME/Library/Application Support"
  ln -sfv "$(brew --prefix)/share/kservices5" "$HOME/Library/Application Support"
  ln -sfv "$(brew --prefix)/share/kservicetypes5" "$HOME/Library/Application Support"
  ln -sfv "$(brew --prefix)/share/kxmlgui5" "$HOME/Library/Application Support"
  ln -sfv "$(brew --prefix)/share/metainfo" "$HOME/Library/Application Support"
  mkdir -pv "$HOME/Applications/KDE"
  ln -sfv "$(brew --prefix)/opt/okular/bin/okular.app" "$HOME/Applications/KDE/"
```

I've solved the bugs for the Annotation Tool.

Okular is really a cool project.

**Comment by diversys** [comment]
@sadhen could you add the same for KolourPaint and Konsole please? Thanks!

**Comment by sadhen** [comment]
@diversys I'd like to post about how to build a retina Qt application on GNU TeXmacs's blog: https://texmacs.github.io/blog/

**Pull request merged**
